spring:
  datasource:
    password: compose-postgres
    username: compose-postgres
    url: jdbc:postgresql://localhost:5423/compose-postgres
  jpa:
    properties:
      hibernate:
        show_sql: true

    hibernate:
      ddl-auto: update
